11/09/2021 22:25:20 - root - INFO - ----------START----------

11/09/2021 22:25:20 - root - INFO - New date are avalable: False
11/09/2021 22:25:20 - root - INFO - Connection with proxy: proxy.voip.plus:8080
11/09/2021 22:25:20 - root - INFO - Check connection
11/09/2021 22:25:20 - root - INFO - While loop, host: ('proxy.voip.plus', 8080)
11/09/2021 22:25:20 - root - INFO - checked
11/09/2021 22:25:20 - root - INFO - Port is open
11/09/2021 22:25:20 - root - INFO - Proxy connected Succesfully

11/09/2021 22:25:20 - root - INFO - Connecting with Proxy: proxy.voip.plus:8080
11/09/2021 22:25:21 - root - INFO - Registration are started

11/09/2021 22:25:21 - root - INFO - Enter Login page
11/09/2021 22:25:25 - root - INFO - User are logged: True
11/09/2021 22:25:36 - root - INFO - No new registration date avalable
11/09/2021 22:25:36 - root - INFO - Waiting for 5min

11/09/2021 22:25:41 - root - INFO - Registration dates chacked: ['18']
11/09/2021 22:25:41 - root - INFO - ----------START----------

11/09/2021 22:25:41 - root - INFO - New date are avalable: False
11/09/2021 22:25:41 - root - INFO - Connection with proxy: proxy.voip.plus:8080
11/09/2021 22:25:41 - root - INFO - Check connection
11/09/2021 22:25:41 - root - INFO - While loop, host: ('proxy.voip.plus', 8080)
11/09/2021 22:25:41 - root - INFO - checked
11/09/2021 22:25:41 - root - INFO - Port is open
11/09/2021 22:25:41 - root - INFO - Proxy connected Succesfully

11/09/2021 22:25:41 - root - INFO - Connecting with Proxy: proxy.voip.plus:8080
11/09/2021 22:25:42 - root - INFO - Registration are started

11/09/2021 22:25:42 - root - INFO - Enter Login page
11/09/2021 22:25:48 - root - INFO - User are logged: True
11/09/2021 22:25:58 - root - INFO - No new registration date avalable
11/09/2021 22:25:58 - root - INFO - Waiting for 5min

11/09/2021 22:26:03 - root - INFO - Registration dates chacked: ['18']
11/09/2021 22:26:03 - root - INFO - ----------START----------

11/09/2021 22:26:03 - root - INFO - New date are avalable: False
11/09/2021 22:26:03 - root - INFO - Connection with proxy: proxy.voip.plus:8080
11/09/2021 22:26:03 - root - INFO - Check connection
11/09/2021 22:26:03 - root - INFO - While loop, host: ('proxy.voip.plus', 8080)
11/09/2021 22:26:03 - root - INFO - checked
11/09/2021 22:26:03 - root - INFO - Port is open
11/09/2021 22:26:03 - root - INFO - Proxy connected Succesfully

11/09/2021 22:26:03 - root - INFO - Connecting with Proxy: proxy.voip.plus:8080
11/09/2021 22:26:04 - root - INFO - Registration are started

11/09/2021 22:26:04 - root - INFO - Enter Login page
11/09/2021 22:26:11 - root - INFO - User are logged: True
11/09/2021 22:26:22 - root - INFO - No new registration date avalable
11/09/2021 22:26:22 - root - INFO - Waiting for 5min

11/09/2021 22:26:27 - root - INFO - Registration dates chacked: ['18']
11/09/2021 22:26:27 - root - INFO - ----------START----------

11/09/2021 22:26:27 - root - INFO - New date are avalable: False
11/09/2021 22:26:27 - root - INFO - Connection with proxy: proxy.voip.plus:8080
11/09/2021 22:26:27 - root - INFO - Check connection
11/09/2021 22:26:27 - root - INFO - While loop, host: ('proxy.voip.plus', 8080)
11/09/2021 22:26:27 - root - INFO - checked
11/09/2021 22:26:27 - root - INFO - Port is open
11/09/2021 22:26:27 - root - INFO - Proxy connected Succesfully

11/09/2021 22:26:27 - root - INFO - Connecting with Proxy: proxy.voip.plus:8080
11/09/2021 22:26:28 - root - INFO - Registration are started

11/09/2021 22:26:28 - root - INFO - Enter Login page
11/09/2021 22:26:28 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3bbccf1040>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/aa7e915ec4f3ed9e23f26dae1d3df6e0
11/09/2021 22:26:28 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3bbcb5bee0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/aa7e915ec4f3ed9e23f26dae1d3df6e0
11/09/2021 22:26:28 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3bbcaf12e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/aa7e915ec4f3ed9e23f26dae1d3df6e0
